name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs every hour, on the hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: YOUR_CHANNEL_ID
          comment_tag_name: YOUTUBE-CARDS
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
          show_duration: true
          background_color: "#0d1117"
          title_color: "#A317EE"
          stats_color: "#00FFFF"
          max_title_lines: 1
          card_width: 250
          border_radius: 5
